name: Update Products Cronjob

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  update_products:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        store: [HHGLOBAL, GNP]
      max-parallel: 1

    env:
      GRAPHQL_URL: ${{ secrets[ format('GRAPHQL_URL_{0}', matrix.store) ] }}
      SHOPIFY_TOKEN: ${{ secrets[ format('SHOPIFY_TOKEN_{0}', matrix.store) ] }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: "18" }
      - run: npm install

      - name: Run update for ${{ matrix.store }}
        run: node index.js
